name: woori-silok-CI/CD

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: |
          cd app
          npm install
          npm run lint-fix
          npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build web app
        run: |
          cd app
          npm install
          npm run build

      - name: Deploy web app
        run: |
          cd cdk
          npm install
          npm run cdk:deploy woori-silok-web-app-stack
        env:
          AWS_DEFAULT_REGION: "ap-northeast-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
